[package]
name = "md4"
version = "0.7.0"
authors = ["The Rust-Crypto Project Developers"]
license = "MIT/Apache-2.0"
description = "MD4 hash function"
documentation = "https://docs.rs/md4"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "md4", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.7"
byte-tools = "0.2"
block-buffer = "0.3"
fake-simd = "0.1"

[dev-dependencies]
crypto-tests = "0.6"

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
